url  https://www.quora.com/Why-do-we-use-AC-supply-in-our-homes/answer/Richard-Muller-3
7279 Upvoters
url  https://www.quora.com/What-is-the-best-way-to-reduce-belly-fat-and-overall-weight/answer/Richard-Muller-3
6725 Upvoters
url  https://www.quora.com/Is-it-true-that-there-is-a-professor-at-UC-Berkeley-who-receives-a-standing-ovation-at-the-end-of-every-lecture-If-so-what-is-his-her-name-and-why/answer/Richard-Muller-3
21989 Upvoters
url  https://www.quora.com/How-will-the-anti-Trump-liberals-react-if-President-Trump-turns-the-nation-around-for-the-better-and-they-cant-say-I-told-you-so/answer/Richard-Muller-3
6696 Upvoters
url  https://www.quora.com/What-is-your-opinion-on-the-UC-Berkeley-protest-against-Milo-Yiannopoulos-Feb-2017/answer/Richard-Muller-3
9124 Upvoters
url  https://www.quora.com/Have-you-ever-scammed-a-scammer-1/answer/Richard-Muller-3
21634 Upvoters
url  https://www.quora.com/Are-there-any-scientists-out-there-on-Quora-who-do-not-believe-in-climate-change/answer/Richard-Muller-3
7508 Upvoters
url  https://www.quora.com/Is-it-possible-to-create-time/answer/Richard-Muller-3
7886 Upvoters
url  https://www.quora.com/Whats-the-most-disturbing-truth-about-marriage/answer/Richard-Muller-3
13312 Upvoters
url  https://www.quora.com/I-just-did-horribly-on-a-test-Is-it-in-poor-taste-to-send-the-professor-an-email-apologizing-and-explaining-that-Ive-been-having-personal-issues/answer/Richard-Muller-3
17686 Upvoters
url  https://www.quora.com/If-a-situation-like-in-the-movie-Martian-arises-would-NASA-or-some-other-space-agency-spend-few-billions-to-save-that-one-person/answer/Richard-Muller-3
6229 Upvoters
url  https://www.quora.com/Is-it-possible-to-solve-every-differential-equation-in-this-world/answer/Richard-Muller-3
6573 Upvoters
url  https://www.quora.com/The-government-says-%E2%80%9CIf-you%E2%80%99re-not-doing-anything-wrong-you-shouldn%E2%80%99t-have-anything-to-hide-%E2%80%9D-If-that-is-true-why-cant-we-know-whats-in-Area-51/answer/Richard-Muller-3
11761 Upvoters
url  https://www.quora.com/What-is-the-difference-between-meters-per-second-and-meters-per-second%C2%B2/answer/Richard-Muller-3
8669 Upvoters
url  https://www.quora.com/What-is-the-most-clever-life-hack-youve-learned/answer/Richard-Muller-3
18054 Upvoters
url  https://www.quora.com/Did-your-child-ever-hear-you-say-a-word-that-they-now-repeat/answer/Richard-Muller-3
