
https://www.quora.com/Why-do-we-use-AC-supply-in-our-homes/answer/Richard-Muller-3
132.6
https://www.quora.com/What-is-the-best-way-to-reduce-belly-fat-and-overall-weight/answer/Richard-Muller-3
144
https://www.quora.com/Is-it-true-that-there-is-a-professor-at-UC-Berkeley-who-receives-a-standing-ovation-at-the-end-of-every-lecture-If-so-what-is-his-her-name-and-why/answer/Richard-Muller-3
275.7
https://www.quora.com/What-are-some-widely-cited-studies-in-the-news-that-are-false/answer/Richard-Muller-3
185
https://www.quora.com/How-will-the-anti-Trump-liberals-react-if-President-Trump-turns-the-nation-around-for-the-better-and-they-cant-say-I-told-you-so/answer/Richard-Muller-3
262.5
https://www.quora.com/What-is-your-opinion-on-the-UC-Berkeley-protest-against-Milo-Yiannopoulos-Feb-2017/answer/Richard-Muller-3
186.3
https://www.quora.com/Have-you-ever-scammed-a-scammer-1/answer/Richard-Muller-3
516.2
https://www.quora.com/Are-CIA-agents-trained-to-be-badasses-like-the-movies-make-them-to-be/answer/Richard-Muller-3
161.9
https://www.quora.com/Are-there-any-scientists-out-there-on-Quora-who-do-not-believe-in-climate-change/answer/Richard-Muller-3
209
https://www.quora.com/Is-it-possible-to-create-time/answer/Richard-Muller-3
223
https://www.quora.com/Why-hasnt-Dr-Vera-Rubin-been-awarded-a-Nobel-Prize-for-Physics/answer/Richard-Muller-3
223
https://www.quora.com/Whats-the-most-disturbing-truth-about-marriage/answer/Richard-Muller-3
380.3
https://www.quora.com/I-just-did-horribly-on-a-test-Is-it-in-poor-taste-to-send-the-professor-an-email-apologizing-and-explaining-that-Ive-been-having-personal-issues/answer/Richard-Muller-3
336.8
https://www.quora.com/If-a-situation-like-in-the-movie-Martian-arises-would-NASA-or-some-other-space-agency-spend-few-billions-to-save-that-one-person/answer/Richard-Muller-3
147.7
https://www.quora.com/Why-is-downloading-a-pirated-copy-of-a-book-condemned-as-stealing-from-the-author-but-not-buying-a-second-hand-book/answer/Richard-Muller-3
108.8
https://www.quora.com/Is-it-possible-to-solve-every-differential-equation-in-this-world/answer/Richard-Muller-3
214.8
https://www.quora.com/The-government-says-%E2%80%9CIf-you%E2%80%99re-not-doing-anything-wrong-you-shouldn%E2%80%99t-have-anything-to-hide-%E2%80%9D-If-that-is-true-why-cant-we-know-whats-in-Area-51/answer/Richard-Muller-3
236.9
